title: CSS Advanced
email: koko@dev.com
description: Hi there!
destination: docs
baseurl: "/first-jekyll"
url: "" 
twitter_username: jjj
github_username:  jjj

# Build settings
plugins:
  - jekyll-feed

exclude: 
  - docs
  - Gemfile
  - Genfile.lock
  - node_modules
  - vendor/bundle
  - vendor/cache
  - vendor/ gems
  - vendor/ ruby
